### ISSUE TITLE
question about adding a new character

### ISSUE THREAD

**Issue by SuperPou1** [HelloOO7/BounceTales#10]
i tried to add a new character that i named helium by copying most of wolly's code but he looks like this:
![obraz](https://github.com/HelloOO7/BounceTales/assets/52333731/2950280e-11c2-44e9-b185-8632b3434466)
any idea why is this happening?

**Comment by HelloOO7** [comment]
That's Bounce's highlight texture.
Also this is a Github issue tracker, not a tech support forum.

**Comment by SuperPou1** [comment]
i'm asking this because it draws fine with bumpy's code for drawing, and is only a dot with bounce's code. am i missing something in how the ball is getting drawn?

**Comment by HelloOO7** [comment]
I don't know. This is an issue tracker of a repo for a decompilation of the game, not a modding community. If you don't have anything concrete that you suspect to be related to a bug in the decompilation, please close this.
