### ISSUE TITLE
can't compose a new texture using bouncetools

### ISSUE THREAD

**Issue by SuperPou1** [HelloOO7/BounceTales#11]
i tried to add a new texture in the graphics folder of res_decomposed, gave it a res file, composed with bouncetools, but the new resource didn't appear in resourceid.java or the res folder in bouncetales. why is that?

**Comment by HelloOO7** [comment]
Most likely because you did not add them to `master.res`. Please take a look at [ResourceComposer](https://github.com/HelloOO7/BounceTales/blob/master/BounceTools/src/bouncetools/ResourceComposer.java) sources in order to grasp how the composition process works.

**Comment by SuperPou1** [comment]
ah ok thanks
