### ISSUE TITLE
adding a texture and recomposing causes the menu text to be black

### ISSUE THREAD

**Issue by SuperPou1** [HelloOO7/BounceTales#12]
i copied BallBumpyCracks res and png files as BallBumpyCracks2, then i added these files to master.res, then i recomposed the resources with bouncetools, and then, even after a clean build, in bounce tales the menu text is black.
here's what it looks like:
![obraz](https://github.com/HelloOO7/BounceTales/assets/52333731/292c4c0a-f514-4181-87a6-333790b71488)

**Comment by HelloOO7** [comment]
This may or may not be a bug. Duplicating a .res file is very incorrect behavior since the sprite IDs in it will then become non-unique. Try to make an edit first that is legal from the perspective of the game code, and if the issue persists, file a proper bug report.
