### ISSUE TITLE
game doesn't start again after making a new game and making any progress

### ISSUE THREAD

**Issue by SuperPou1** [HelloOO7/BounceTales#2]
So, what i discovered, is that both in the s40 sdk and on real hardware, if i compile the game without changing any code, then the game is broken - if you make a new game and make any progress (for example finish the first chapter) then if you exit out of the app and run it again, it gets stuck at the bounce tales logo on white background

**Comment by SuperPou1** [comment]
(by real hardware i mean my nokia c5-00 which runs symbian s60v3)

**Comment by HelloOO7** [comment]
Does this also happen when you use a cheat code in the main menu instead of progressing naturally (000 or 111 on the keypad)?
Is the same behavior exhibited when running through Jademula?

I can't reproduce this on neither the S40 SDK nor my Nokia E51 on master/#[c0c3407](https://github.com/HelloOO7/BounceTales/commit/c0c340781ecbf1ba3bcb62d1516c4a120f48d426).

**Comment by SuperPou1** [comment]
well i get a bunch of errors like this:
```
	at java.lang.RuntimeExceptionb
ouncetales.GameRuntime.startLoadScene(+15)
	at bouncetales.BounceGame.updateLoadingScreen(BounceGame.java:1256)
	at bouncetales.BounceGame.paint(+137)
	at bouncetales.GameRuntime.gamePaint(GameRuntime.java:887)
	at bouncetales.GameRuntime.callGamePaint(GameRuntime.java:927)
	at bouncetales.GameRuntime.run(+44)
	atjava.lang.RuntimeException 
```
which repeat all the time when the game is on the logo screen

**Comment by HelloOO7** [comment]
Those line numbers don't seem to match up. Are you sure you are on the correct commit?

**Comment by SuperPou1** [comment]
what about now?
```
at java.lang.RuntimeExceptionb
ouncetales.GameRuntime.startLoadScene(+15)
	at bouncetales.BounceGame.updateLoadingScreen(BounceGame.java:1282)
	at bouncetales.BounceGame.paint(+137)
	at bouncetales.GameRuntime.gamePaint(GameRuntime.java:885)
	at bouncetales.GameRuntime.callGamePaint(GameRuntime.java:925)
	at bouncetales.GameRuntime.run(+44)
	java.lang.RuntimeException
```

**Comment by SuperPou1** [comment]
> Does this also happen when you use a cheat code in the main menu instead of progressing naturally (000 or 111 on the keypad)? Is the same behavior exhibited when running through Jademula?
> 
> I can't reproduce this on neither the S40 SDK nor my Nokia E51 on master/#[c0c3407](https://github.com/HelloOO7/BounceTales/commit/c0c340781ecbf1ba3bcb62d1516c4a120f48d426).

yes, in this case, it also happens
also, didn't know that cheatcode existed! i played this game for over 10 years now!

**Comment by SuperPou1** [comment]
oh wait
did you add the cheatcode?

**Comment by HelloOO7** [comment]
Check the output log to see if maybe the loading thread has died before the game could start. I still can't reproduce this.

>  also, didn't know that cheatcode existed! i played this game for over 10 years now!

The game doesn't have cheats enabled unless you edit the MANIFEST.MF to add a "Cheats: On" property, so even though it did exist, you most likely couldn't use it.

**Comment by SuperPou1** [comment]
> Check the output log to see if maybe the loading thread has died before the game could start. I still can't reproduce this.
> 
> > also, didn't know that cheatcode existed! i played this game for over 10 years now!
> 
> The game doesn't have cheats enabled unless you edit the MANIFEST.MF to add a "Cheats: On" property, so even though it did exist, you most likely couldn't use it.

by the way, important detail: the errors don't happen until you press the "ok" button (the middle navigation button)

**Comment by SuperPou1** [comment]
do you want the log from the start and to when the error happens?

**Comment by HelloOO7** [comment]
I can compile the project into a JAR, run it on the S40 emulator and load my cheated save data just fine.
An error log would be great, but please set aside the duplicate exception traces.

**Comment by SuperPou1** [comment]
here you go:
```
"Series 40 5th Edition SDK,  Feature Pack 1" Instance #6500500 Ready for Future Connections
Using Untrusted simulated domain
New game state 1
Starting BounceThread
Initializing game
LocalizedData init...
Check Nokia-Platform  Nokia* against Nokia6500s-1/04.80
LocalizedData init success.
Starting BounceThread
Loading saved data...
New game state 5
	at java.lang.RuntimeExceptionb
ouncetales.GameRuntime.startLoadScene(+15)
```

**Comment by HelloOO7** [comment]
Okay, seems to be some issue with your save data. Still can't reproduce it, but can you try with #[04ebec9](https://github.com/HelloOO7/BounceTales/commit/04ebec94aa9e2fc8ab2c1846748ef5764eb497fa)?

**Comment by SuperPou1** [comment]
now something is REALLY wrong, i get this:
```
New game state 1
Starting BounceThread
Initializing game
LocalizedData init...
Check Nokia-Platform  Nokia* against Nokia6500s-1/04.80
LocalizedData init success.
Starting BounceThread
Loading saved data...
Saved data loaded
Loading screen thread ended
Starting BounceThread
Bounce setUI 17
Loading screen thread ended
```

**Comment by SuperPou1** [comment]
![image](https://user-images.githubusercontent.com/52333731/211682361-e5062733-5cb0-4282-99d1-d797ef974ef1.png)
dude, it literally froze the sdk, now it's a weapon of death

**Comment by HelloOO7** [comment]
That might be a Wine issue. The output you sent looks OK to me, and running with a clean save, beating one level and reloading the save works as well. Does your S40 device exhibit a similar behavior?

**Comment by SuperPou1** [comment]
lemme check, also it's a s60 device, but i guess it's close enough, tho it runs the original version fine

**Comment by SuperPou1** [comment]
also what i noticed, is that the original version loads much longer than yours, but it might just be that i have a full save with all chapters beaten, also i now fully closed wine, and i still hear the music sometimes kicking in… creepy

**Comment by SuperPou1** [comment]
yeah, i guess that fixed it! it works completly fine on my nokia!

**Comment by HelloOO7** [comment]
It doesn't actually load that long, it's that the splash screen is set to display for a grueling 3 seconds. Mine does it in 0,1 cause it would be super annoying having to wait for that every time I want to test something. You can change that in BounceGame.java in `SPLASH_SCREEN_DURATIONS`.

**Comment by SuperPou1** [comment]
ok, thanks, so issue fixed!

**Comment by SuperPou1** [comment]
i guess i just can't test the game in the sdk now…
