### ISSUE TITLE
Decompiler

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [HelloOO7/BounceTales#3]
Hello! Which decompiler have you used?

**Comment by HelloOO7** [comment]
From what I can recall:

- JADX 1.2.0 (newer versions have a regression that hides int->long casts and as such breaks fixed point arithmetics).
- Procyon for methods that JADX was unable to decompile.
- Recaf's disassembler for reconstructing improperly decompiled logic sometimes produced by the former.

**Comment by Nikita-Sherstnev** [comment]
Thank you very much! I'll try to conquer some games.
