### ISSUE TITLE
no package called xstandard in bouncetools

### ISSUE THREAD

**Issue by SuperPou1** [HelloOO7/BounceTales#4]
![image](https://github.com/HelloOO7/BounceTales/assets/52333731/c85c0fb0-650e-44c3-94f3-7b2f8b8eff49)
i cannot run bouncetools because of this, am i missing something?

**Comment by HelloOO7** [comment]
Have you cloned the repo recursively?

**Comment by SuperPou1** [comment]
i just clicked on "code" and pressed download

**Comment by HelloOO7** [comment]
Since stuff like Jademula or XStandard is contained in submodules, you must do a proper recursive clone through Git. The web downloads won't suffice.

**Comment by SuperPou1** [comment]
alright, i cloned it recursively and now it works! thanks!
