### ISSUE TITLE
bouncetools gets stuck at decomposing after selecting bounce tales jar

### ISSUE THREAD

**Issue by SuperPou1** [HelloOO7/BounceTales#6]
![image](https://github.com/HelloOO7/BounceTales/assets/52333731/a70b2b5d-f135-42b6-b162-e62e4cda8cf6)
how do i fix this?

**Comment by HelloOO7** [comment]
Read step 1 of the Build instructions of BounceWin32 (dependency of BounceTools) for Windows.

**Comment by SuperPou1** [comment]
i'm not exactly sure how to do that step, can you help?

**Comment by SuperPou1** [comment]
nevermind, i figured it out
